name: uix
version: 0.0.1
author: Boris Kaul <localvoid@gmail.com>
description: Library to build User Interfaces
homepage: https://github.com/localvoid/uix
environment:
  sdk: '>=1.9.0-dev'
dependencies:
  collection: '^0.2.4'
  source_gen: '^1.1.0'
dev_dependencies:
  unittest: any
