name: uix
version: 0.1.1
author: Boris Kaul <localvoid@gmail.com>
description: Library to build User Interfaces
homepage: https://github.com/localvoid/uix
environment:
  sdk: '>=1.9.0-dev'
dependencies:
  collection: '^1.1.0'
  source_gen: '^0.2.4'
dev_dependencies:
  browser: any
  unittest: any
