name: uix
version: 0.0.1
author: Boris Kaul <localvoid@gmail.com>
description: Library to build User Interfaces
homepage: https://github.com/localvoid/uix
environment:
  sdk: '>=1.9.0-dev'
dependencies:
  collection: any
  source_gen: any
dev_dependencies:
  unittest: any
